### PR TITLE
Terraform 0.13 and staging fixes

### PR DESCRIPTION
**Pull request by danielhoherd**
Changes to make this work in terraform 0.13 and fix staging.

Related to:
- https://github.com/astronomer/issues/issues/3490
- https://github.com/astronomer/terraform-google-astronomer-cloud/pull/154
- https://github.com/astronomer/terraform-kubernetes-astronomer-system-components/pull/23

### CODE REVIEW

**Comment by danielhoherd** [comment]
@pgvishnuram this is broken because of helm terraform module changes. Are you familiar with this change? This module needed updates to work with terraform 0.13 in the staging setup.

**Comment by pgvishnuram** [comment]
@danielhoherd working on this

**Comment by pgvishnuram** [comment]
@danielhoherd  testing full flow - will let you know

**Comment by pgvishnuram** [comment]
@danielhoherd we can merge this. Any how this wont work unless we move to helm3

**Pull request merged**
